all:
  hosts:
    sentinel-prod:
      ansible_host: "CHANGE_ME_VM_PUBLIC_IP"
      ansible_user: "root"
      ansible_ssh_private_key_file: "CHANGE_ME_PATH_TO_SSH_KEY"
  vars:
    app_dir: "/opt/sentinel"
    docker_compose_version: "2.27.0"
    sentinel_version: "latest"
    database_password: "{{ lookup('env', 'SENTINEL_DB_PASSWORD') | default('CHANGE_ME_DB_PASSWORD', true) }}"
    jwt_secret_key: "{{ lookup('env', 'SENTINEL_JWT_SECRET') | default('CHANGE_ME_JWT_SECRET', true) }}"
    grafana_password: "{{ lookup('env', 'SENTINEL_GRAFANA_PASSWORD') | default('CHANGE_ME_GRAFANA_PASSWORD', true) }}"
    nasa_api_key: "{{ lookup('env', 'NASA_API_KEY') | default('', true) }}"
