FROM node:22-alpine

WORKDIR /app

RUN mkdir -p contracts

COPY docker/init/hardhat.config.js /app/hardhat.config.js

RUN npm init -y && npm pkg set type="module" && npm install hardhat

EXPOSE 8545

CMD ["npx", "hardhat", "node", "--hostname", "0.0.0.0", "--port", "8545"]
